shelves=["PineIsland"]
data_dir="/oak/stanford/groups/cyaolai/AashrayChegu/PIG/output-data"
data_product_name = "pine_island_comprehensive"
template = "pine_island_comprehensive.yaml"
boundary_smoothing = 250

[time_mappings.1]
velocity = ["2009-09-15_velocity.nc"]
thickness = ["2009-09-15_thickness.nc"]

[time_mappings.2]
velocity = ["2009-09-15_square-clipped_velocity.nc"]
thickness = ["2009-09-15_thickness.nc"]

[time_mappings.3]
velocity = ["2011-11-30_velocity.nc"]
thickness = ["2011-11-30_thickness.nc"]

[time_mappings.4]
velocity = ["2012-07-01_velocity.nc"]
thickness = ["2012-07-01_thickness.nc"]

[time_mappings.5]
velocity = ["2013-06-01_velocity.nc"]
thickness = ["2013-06-01_thickness.nc"]

[time_mappings.6]
velocity = ["2014-01-30_velocity.nc"]
thickness = ["2014-01-30_thickness.nc"]

[time_mappings.7]
velocity = ["2014-08-01_velocity.nc"]
thickness = ["2014-08-01_thickness.nc"]

[time_mappings.8]
velocity = ["2015-01-01_velocity.nc"]
thickness = ["2015-01-01_thickness.nc"]

[time_mappings.9]
velocity = ["2015-01-01_separated_velocity.nc"]
thickness = ["2015-01-01_thickness.nc"]

[time_mappings.10]
velocity = ["2015-05-16_velocity.nc"]
thickness = ["2015-05-16_thickness.nc"]

[time_mappings.11]
velocity = ["2015-06-01_velocity.nc"]
thickness = ["2015-06-01_thickness.nc"]

[time_mappings.12]
velocity = ["2015-08-15_velocity.nc"]
thickness = ["2015-08-15_thickness.nc"]

[time_mappings.13]
velocity = ["2015-08-15_separated_velocity.nc"]
thickness = ["2015-08-15_thickness.nc"]

[time_mappings.14]
velocity = ["2015-11-15_velocity.nc"]
thickness = ["2015-11-15_thickness.nc"]

[time_mappings.15]
velocity = ["2015-11-15_separated_velocity.nc"]
thickness = ["2015-11-15_thickness.nc"]

[time_mappings.16]
velocity = ["2016-02-15_velocity.nc"]
thickness = ["2016-02-15_thickness.nc"]

[time_mappings.17]
velocity = ["2016-05-16_velocity.nc"]
thickness = ["2016-05-16_thickness.nc"]

[time_mappings.18]
velocity = ["2016-08-15_velocity.nc"]
thickness = ["2016-08-15_thickness.nc"]

[time_mappings.19]
velocity = ["2016-11-15_velocity.nc"]
thickness = ["2016-11-15_thickness.nc"]

[time_mappings.20]
velocity = ["2017-02-14_velocity.nc"]
thickness = ["2017-02-14_thickness.nc"]

[time_mappings.21]
velocity = ["2017-05-16_velocity.nc"]
thickness = ["2017-05-16_thickness.nc"]

[time_mappings.22]
velocity = ["2017-08-15_velocity.nc"]
thickness = ["2017-08-15_thickness.nc"]

[time_mappings.23]
velocity = ["2017-11-15_velocity.nc"]
thickness = ["2017-11-15_thickness.nc"]

[time_mappings.24]
velocity = ["2018-02-14_velocity.nc"]
thickness = ["2018-02-14_thickness.nc"]

[time_mappings.25]
velocity = ["2018-05-16_velocity.nc"]
thickness = ["2018-05-16_thickness.nc"]

[time_mappings.26]
velocity = ["2018-08-15_velocity.nc"]
thickness = ["2018-08-15_thickness.nc"]

[time_mappings.27]
velocity = ["2018-11-15_velocity.nc"]
thickness = ["2018-11-15_thickness.nc"]

[time_mappings.28]
velocity = ["2019-02-14_velocity.nc"]
thickness = ["2019-02-14_thickness.nc"]

[time_mappings.29]
velocity = ["2019-05-16_velocity.nc"]
thickness = ["2019-05-16_thickness.nc"]

[time_mappings.30]
velocity = ["2019-08-15_velocity.nc"]
thickness = ["2019-08-15_thickness.nc"]

[time_mappings.31]
velocity = ["2019-11-15_velocity.nc"]
thickness = ["2019-11-15_thickness.nc"]

[time_mappings.32]
velocity = ["2020-02-15_velocity.nc"]
thickness = ["2020-02-15_thickness.nc"]

[time_mappings.33]
velocity = ["2020-05-16_velocity.nc"]
thickness = ["2020-05-16_thickness.nc"]

[time_mappings.34]
velocity = ["2016-02-15_separated_velocity.nc"]
thickness = ["2016-02-15_thickness.nc"]

[time_mappings.35]
velocity = ["2016-05-16_separated_velocity.nc"]
thickness = ["2016-05-16_thickness.nc"]

[time_mappings.36]
velocity = ["2016-08-15_separated_velocity.nc"]
thickness = ["2016-08-15_thickness.nc"]

[time_mappings.37]
velocity = ["2016-11-15_separated_velocity.nc"]
thickness = ["2016-11-15_thickness.nc"]

[time_mappings.38]
velocity = ["2017-02-14_separated_velocity.nc"]
thickness = ["2017-02-14_thickness.nc"]

[time_mappings.39]
velocity = ["2017-05-16_separated_velocity.nc"]
thickness = ["2017-05-16_thickness.nc"]

[time_mappings.40]
velocity = ["2017-08-15_separated_velocity.nc"]
thickness = ["2017-08-15_thickness.nc"]

[time_mappings.41]
velocity = ["2017-08-15_breakaway_separated_velocity.nc"]
thickness = ["2017-08-15_thickness.nc"]

[time_mappings.42]
velocity = ["2017-11-15_separated_velocity.nc"]
thickness = ["2017-11-15_thickness.nc"]

[time_mappings.43]
velocity = ["2018-02-14_separated_velocity.nc"]
thickness = ["2018-02-14_thickness.nc"]

[time_mappings.44]
velocity = ["2018-05-16_separated_velocity.nc"]
thickness = ["2018-05-16_thickness.nc"]

[time_mappings.45]
velocity = ["2018-08-15_separated_velocity.nc"]
thickness = ["2018-08-15_thickness.nc"]

[time_mappings.46]
velocity = ["2018-11-15_separated_velocity.nc"]
thickness = ["2018-11-15_thickness.nc"]

[time_mappings.47]
velocity = ["2019-02-14_separated_velocity.nc"]
thickness = ["2019-02-14_thickness.nc"]

[time_mappings.48]
velocity = ["2019-05-16_separated_velocity.nc"]
thickness = ["2019-05-16_thickness.nc"]

[time_mappings.49]
velocity = ["2019-08-15_separated_velocity.nc"]
thickness = ["2019-08-15_thickness.nc"]

[time_mappings.50]
velocity = ["2019-11-15_separated_velocity.nc"]
thickness = ["2019-11-15_thickness.nc"]

[time_mappings.51]
velocity = ["2020-02-15_separated_velocity.nc"]
thickness = ["2020-02-15_thickness.nc"]

[time_mappings.52]
velocity = ["2020-05-16_separated_velocity.nc"]
thickness = ["2020-05-16_thickness.nc"]

[time_mappings.53]
velocity = ["2009-09-15_square-clipped_thresholded_velocity.nc"]
thickness = ["2009-09-15_thickness.nc"]

[time_mappings.54]
velocity = ["2011-11-30_thresholded_velocity.nc"]
thickness = ["2011-11-30_thickness.nc"]

[time_mappings.55]
velocity = ["2012-07-01_thresholded_velocity.nc"]
thickness = ["2012-07-01_thickness.nc"]

[time_mappings.56]
velocity = ["2013-06-01_thresholded_velocity.nc"]
thickness = ["2013-06-01_thickness.nc"]

[time_mappings.57]
velocity = ["2014-01-30_thresholded_velocity.nc"]
thickness = ["2014-01-30_thickness.nc"]

[time_mappings.58]
velocity = ["2014-08-01_thresholded_velocity.nc"]
thickness = ["2014-08-01_thickness.nc"]

[time_mappings.59]
velocity = ["2015-01-01_thresholded_velocity.nc"]
thickness = ["2015-01-01_thickness.nc"]

[time_mappings.60]
velocity = ["2015-05-16_thresholded_velocity.nc"]
thickness = ["2015-05-16_thickness.nc"]

[time_mappings.61]
velocity = ["2015-06-01_thresholded_velocity.nc"]
thickness = ["2015-06-01_thickness.nc"]

[time_mappings.62]
velocity = ["2015-08-15_thresholded_velocity.nc"]
thickness = ["2015-08-15_thickness.nc"]

[time_mappings.63]
velocity = ["2015-11-15_thresholded_velocity.nc"]
thickness = ["2015-11-15_thickness.nc"]

[time_mappings.64]
velocity = ["2016-02-15_thresholded_velocity.nc"]
thickness = ["2016-02-15_thickness.nc"]

[time_mappings.65]
velocity = ["2016-05-16_thresholded_velocity.nc"]
thickness = ["2016-05-16_thickness.nc"]

[time_mappings.66]
velocity = ["2016-08-15_thresholded_velocity.nc"]
thickness = ["2016-08-15_thickness.nc"]

[time_mappings.67]
velocity = ["2016-11-15_thresholded_velocity.nc"]
thickness = ["2016-11-15_thickness.nc"]

[time_mappings.68]
velocity = ["2017-02-14_thresholded_velocity.nc"]
thickness = ["2017-02-14_thickness.nc"]

[time_mappings.69]
velocity = ["2017-05-16_thresholded_velocity.nc"]
thickness = ["2017-05-16_thickness.nc"]

[time_mappings.70]
velocity = ["2017-08-15_thresholded_velocity.nc"]
thickness = ["2017-08-15_thickness.nc"]

[time_mappings.71]
velocity = ["2017-08-15_breakaway_thresholded_velocity.nc"]
thickness = ["2017-08-15_thickness.nc"]

[time_mappings.72]
velocity = ["2017-11-15_thresholded_velocity.nc"]
thickness = ["2017-11-15_thickness.nc"]

[time_mappings.73]
velocity = ["2018-02-14_thresholded_velocity.nc"]
thickness = ["2018-02-14_thickness.nc"]

[time_mappings.74]
velocity = ["2018-05-16_thresholded_velocity.nc"]
thickness = ["2018-05-16_thickness.nc"]

[time_mappings.75]
velocity = ["2018-08-15_thresholded_velocity.nc"]
thickness = ["2018-08-15_thickness.nc"]

[time_mappings.76]
velocity = ["2018-11-15_thresholded_velocity.nc"]
thickness = ["2018-11-15_thickness.nc"]

[time_mappings.77]
velocity = ["2019-02-14_thresholded_velocity.nc"]
thickness = ["2019-02-14_thickness.nc"]

[time_mappings.78]
velocity = ["2019-05-16_thresholded_velocity.nc"]
thickness = ["2019-05-16_thickness.nc"]

[time_mappings.79]
velocity = ["2019-08-15_thresholded_velocity.nc"]
thickness = ["2019-08-15_thickness.nc"]

[time_mappings.80]
velocity = ["2019-11-15_thresholded_velocity.nc"]
thickness = ["2019-11-15_thickness.nc"]

[time_mappings.81]
velocity = ["2020-02-15_thresholded_velocity.nc"]
thickness = ["2020-02-15_thickness.nc"]

[time_mappings.82]
velocity = ["2020-05-16_thresholded_velocity.nc"]
thickness = ["2020-05-16_thickness.nc"]

[time_mappings.83]
velocity = ["2009-09-15_square-clipped_HT-thresholded_velocity.nc"]
thickness = ["2009-09-15_thickness.nc"]

[time_mappings.84]
velocity = ["2011-11-30_HT-thresholded_velocity.nc"]
thickness = ["2011-11-30_thickness.nc"]

[time_mappings.85]
velocity = ["2012-07-01_HT-thresholded_velocity.nc"]
thickness = ["2012-07-01_thickness.nc"]

[time_mappings.86]
velocity = ["2013-06-01_HT-thresholded_velocity.nc"]
thickness = ["2013-06-01_thickness.nc"]

[time_mappings.87]
velocity = ["2014-01-30_HT-thresholded_velocity.nc"]
thickness = ["2014-01-30_thickness.nc"]

[time_mappings.88]
velocity = ["2014-08-01_HT-thresholded_velocity.nc"]
thickness = ["2014-08-01_thickness.nc"]

[time_mappings.89]
velocity = ["2015-01-01_HT-thresholded_velocity.nc"]
thickness = ["2015-01-01_thickness.nc"]

[time_mappings.90]
velocity = ["2015-05-16_HT-thresholded_velocity.nc"]
thickness = ["2015-05-16_thickness.nc"]

[time_mappings.91]
velocity = ["2015-06-01_HT-thresholded_velocity.nc"]
thickness = ["2015-06-01_thickness.nc"]

[time_mappings.92]
velocity = ["2015-08-15_HT-thresholded_velocity.nc"]
thickness = ["2015-08-15_thickness.nc"]

[time_mappings.93]
velocity = ["2015-11-15_HT-thresholded_velocity.nc"]
thickness = ["2015-11-15_thickness.nc"]

[time_mappings.94]
velocity = ["2016-02-15_HT-thresholded_velocity.nc"]
thickness = ["2016-02-15_thickness.nc"]

[time_mappings.95]
velocity = ["2016-05-16_HT-thresholded_velocity.nc"]
thickness = ["2016-05-16_thickness.nc"]

[time_mappings.96]
velocity = ["2016-08-15_HT-thresholded_velocity.nc"]
thickness = ["2016-08-15_thickness.nc"]

[time_mappings.97]
velocity = ["2016-11-15_HT-thresholded_velocity.nc"]
thickness = ["2016-11-15_thickness.nc"]

[time_mappings.98]
velocity = ["2017-02-14_HT-thresholded_velocity.nc"]
thickness = ["2017-02-14_thickness.nc"]

[time_mappings.99]
velocity = ["2017-05-16_HT-thresholded_velocity.nc"]
thickness = ["2017-05-16_thickness.nc"]

[time_mappings.100]
velocity = ["2017-08-15_HT-thresholded_velocity.nc"]
thickness = ["2017-08-15_thickness.nc"]

[time_mappings.101]
velocity = ["2017-08-15_breakaway_HT-thresholded_velocity.nc"]
thickness = ["2017-08-15_thickness.nc"]

[time_mappings.102]
velocity = ["2017-11-15_HT-thresholded_velocity.nc"]
thickness = ["2017-11-15_thickness.nc"]
